### ISSUE TITLE
Setting an input[type=date] with a date should warn

### ISSUE THREAD

**Issue by matthewp** [canjs/can-attribute-observable#41]
If you attempt to set an `<input type=date>` element using a Date, can-attribute-observable converts it to a string using toString(), but the element will not accept it in the format.

We should probably special-case this scenario so that it is set correctly.

**Comment by matthewp** [comment]
Going to create a warning instead.

**Comment by matthewp** [comment]
Is this an OK warning? Are there any similar warnings I can look at?

<img width="1179" alt="Screen Shot 2019-10-21 at 2 56 04 PM" src="https://user-images.githubusercontent.com/361671/67295348-fdbfb200-f4b4-11e9-9f04-46a70f78220a.png">

**Comment by chasenlehara** [comment]
Could you link to the `valueAsDate` docs as well?

**Comment by matthewp** [comment]
Do you mean the MDN docs? It's listed on the docs for HTMLInputElement, but can't be directly linked to. I wonder if we should have a page for this in our own docs 🤔

**Comment by chasenlehara** [comment]
I hadn’t looked for this before but I assumed we had docs on it. I would add a “Date input” section to the [common form elements guide](https://canjs.com/doc/guides/forms.html#Commonformelements) and link to that in the warning. 🤷‍♂️

**Comment by matthewp** [comment]
I've done so, thanks for the idea @chasenlehara!

**Comment by matthewp** [comment]
Fixed in #43, canjs/canjs release coming soon.
